---
# ansible/roles/postgresql/handlers/main.yml

- name: restart postgresql
  ansible.builtin.systemd:
    name: "postgresql@{{ pg_version }}-main"
    state: restarted
  become: true

- name: reload postgresql
  ansible.builtin.systemd:
    name: "postgresql@{{ pg_version }}-main"
    state: reloaded
  become: true
