---
# ansible/roles/haproxy/handlers/main.yml

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: reload haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: reloaded
  become: true
